CREATE TABLE employee
(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) DEFAULT NULL,
    salary DOUBLE DEFAULT NULL
);

CREATE TABLE student
(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) DEFAULT NULL,
    passport VARCHAR(255) DEFAULT NULL
);